### ISSUE TITLE
Override `Vector` operators in `Point2` and `Point3` with the correct return type

### ISSUE THREAD

**Issue by luisenp** [facebookresearch/theseus#113]
## 🚀 Feature

Something like 

```python
class Point2(Vector):
    ...
    
    def __add__(self, other: Vector) -> "Point2":
        return cast(Point2, super().__add__(other))
```

## Motivation

Eliminates unnecessary casting when using typing. 

## Alternatives

There might be some way for `mypy` to do the correct thing that wouldn't require overriding these methods.

**Comment by jeffin07** [comment]
@luisenp I am intrested in this Can you please guide me ?

**Comment by jeffin07** [comment]
@luisenp Is this issue assinged to anyone ? Or do you want me to pick another one ?

**Comment by luisenp** [comment]
Hi @jeffin07, no, in fact it'd be great if you can take a look at this one! Sorry for the delay, I've been busy this week, so I forgot about this issue. 

We have a `Vector` class for our optimization variables, which in turn has two subclasses,`Point2` and `Point3`. `Vector` [overrides](https://github.com/facebookresearch/theseus/blob/main/theseus/geometry/vector.py#L94) a lot of the Python operators so that we can do things like `x + y`, `x * y`, and so on. The point subclasses inherit these operators, but when using `mypy` for typing, doing something like the code below will throw a typing error. 

```python
x = th.Point2(...)
y = th.Point2(...)
z = x + y
out = function_expects_point2(z)  # mypy errors here because z is th.Vector, not th.Point2
```

So, the goal of this issue is to override the operators in the subclasses, to avoid this typing issue. The obvious way would be to do something like what I described in the original comment above, inside classes [Point2](https://github.com/facebookresearch/theseus/blob/main/theseus/geometry/point_types.py#L29) and [Point3](https://github.com/facebookresearch/theseus/blob/main/theseus/geometry/point_types.py#L103).  

Let me know if that makes sense, and thanks!

**Comment by jeffin07** [comment]
@luisenp So we need to override `add`,`sub`,`mul`,`truediv`,`matmul` functions right ?

**Comment by luisenp** [comment]
Yes, and there are a few others as well, but we can start with those for now.
