### ISSUE TITLE
Minor issue on homography estimation example

### ISSUE THREAD

**Issue by luizgh** [facebookresearch/theseus#274]
## 🐛 Bug

The homography estimation example fails if you run it without having a "examples/data/" folder. The current code tries to download the dataset to the "data" folder before creating it: https://github.com/facebookresearch/theseus/blob/main/examples/homography_estimation.py#L54

## Steps to Reproduce

1. Ensure you don't have a "data" folder under the examples
2. Run python homography_estimation.py

## Expected behavior

Expected the demo to run, but it gives the errors below:

```
Running command:  wget http://ptak.felk.cvut.cz/revisitop/revisitop1m/jpg//revisitop1m.1.tar.gz -O <my_path_here>/theseus/examples/data/revisitop1m.1.tar.gz
<my_path_here>/theseus/examples/data/revisitop1m.1.tar.gz: No such file or directory
Running command:  tar -xf <my_path_here>/theseus/examples/data/revisitop1m.1.tar.gz -C <my_path_here>/theseus/examples/data/revisitop1m.1
tar: <my_path_here>/theseus/examples/data/revisitop1m.1.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "homography_estimation.py", line 417, in <module>
    main()
  File "homography_estimation.py", line 412, in main
    run()
  File "homography_estimation.py", line 291, in run
    dataset = HomographyDataset(dataset_paths, imgH, imgW)
  File "homography_estimation.py", line 70, in __init__
    assert len(self.img_paths) > 0, "no images found"
AssertionError: no images found
```

## Additional context

Solution is simple: just run the mkdir before the wget. I can create a PR if needed, but it's such a small change that it can be added to something else.

## System Info

- OS (e.g., Linux): Ubuntu 20.04 (WSL)
- Python version: 3.8.13
- GPU models and configuration: N/A
- CUDA version: N/A
- pip/conda dependencies packages versions: N/A
- Any other relevant information: N/A

**Comment by mhmukadam** [comment]
Thanks for pointing our the bug, @luizgh! Small PRs are most welcome, if you would like to submit a quick fix :)
