### ISSUE TITLE
Updating just `aux_vars` isn't sufficient to re-solve with some data changed 

### ISSUE THREAD

**Issue by bamos** [facebookresearch/theseus#28]
## 🐛 Bug

Using the quadratic fit example, I thought it would be reasonable to update the data in just `aux_vars` and re-solve, but it seems like there's a dependence on the global data_x.

## Steps to Reproduce

I included a MWE below that outputs the incorrect solution in the middle here by just changing `aux_inputs`:

```
optimal a:  tensor([[1.0076]], grad_fn=<AddBackward0>)
== Only changing aux_vars["x"] (this should not be the same solution)
optimal a:  tensor([[1.0076]], grad_fn=<AddBackward0>)
== Globally updating data_x (this is the correct solution)
optimal a:  tensor([[0.0524]], grad_fn=<AddBackward0>)
```

## Expected behavior

I was pretty confused at first when my code using wasn't working and didn't realize it was because of this. We should make updating `aux_inputs` sufficient to re-solve the problem, or if this is challenging we should consider 1) raising a warning/adding a check with `aux_inputs` doesn't match or 2) remove duplicated passing of `aux_inputs` when it doesn't do anything.

## Code

```python
#!/usr/bin/env python3

import torch
import theseus as th
import theseus.optimizer.nonlinear as thnl

import numpy as np
import numdifftools as nd

def generate_data(num_points=10, a=1., b=0.5, noise_factor=0.01):
    data_x = torch.rand((1, num_points))
    noise = torch.randn((1, num_points)) * noise_factor
    data_y = a * data_x.square() + b + noise
    return data_x, data_y

num_points = 10
data_x, data_y = generate_data(num_points)

x = th.Variable(data_x.requires_grad_(), name="x")
y = th.Variable(data_y.requires_grad_(), name="y")
a = th.Vector(1, name="a")
b = th.Vector(1, name="b")

def quad_error_fn(optim_vars, aux_vars):
    a, b = optim_vars
    x, y = aux_vars
    est = a.data * x.data.square() + b.data
    err = y.data - est
    return err

optim_vars = a, b
aux_vars = x, y
cost_function = th.AutoDiffCostFunction(
    optim_vars, quad_error_fn, num_points, aux_vars=aux_vars, name="quadratic_cost_fn"
)
objective = th.Objective()
objective.add(cost_function)
optimizer = th.GaussNewton(
    objective,
    max_iterations=15,
    step_size=0.5,
)

theseus_inputs = {
"a": 2 * torch.ones((1, 1)).requires_grad_(),
"b": torch.ones((1, 1)).requires_grad_()
}
aux_vars = {
"x": data_x,
"y": data_y,
}
theseus_optim = th.TheseusLayer(optimizer)
updated_inputs, info = theseus_optim.forward(
    theseus_inputs, aux_vars=aux_vars,
    track_best_solution=True, verbose=False,
    backward_mode=thnl.BackwardMode.FULL,
)
print('optimal a: ', updated_inputs['a'])

aux_vars = {
"x": data_x+10.,
"y": data_y,
}
updated_inputs, info = theseus_optim.forward(
    theseus_inputs, aux_vars=aux_vars,
    track_best_solution=True, verbose=False,
    backward_mode=thnl.BackwardMode.FULL,
)
print('== Only changing aux_vars["x"] (this should not be the same solution)')
print('optimal a: ', updated_inputs['a'])

data_x.data += 10.
aux_vars = {
"x": data_x,
"y": data_y,
}
updated_inputs, info = theseus_optim.forward(
    theseus_inputs, aux_vars=aux_vars,
    track_best_solution=True, verbose=False,
    backward_mode=thnl.BackwardMode.FULL,
)
print('== Globally updating data_x (this is the correct solution)')
print('optimal a: ', updated_inputs['a'])
```

**Comment by bamos** [comment]
Thanks for the quick debug @luisenp! It works if I set this in `theseus_inputs` rather than `aux_vars`, changing the middle part to:

```
theseus_inputs['x'] = data_x+10.,
aux_vars = {
"y": data_y,
}
updated_inputs, info = theseus_optim.forward(
    theseus_inputs, aux_vars=aux_vars,
    track_best_solution=True, verbose=False,
    backward_mode=thnl.BackwardMode.FULL,
)
print('optimal a: ', updated_inputs['a'])
```

**Comment by vshobha** [comment]
It looks like our use of `aux_vars` in `TheseusLayer.forward` has a different meaning than its use in `CostFunction` subclasses. We should probably fix this: this API is a little confusing.

**Comment by luisenp** [comment]
This what my takeaway from this issue as well. Agree that unifying the API here would be less confusing. In particular, there is currently no `aux_vars` argument in `TheseusLayer.forward`, so my first proposal would be to split `input_data` [here](https://github.com/facebookresearch/theseus/blob/main/theseus/theseus_layer.py#L24) into two dictionary argumetns, one for `optim_vars` (setting initial values for the optimization variables) and one for `aux_vars` (setting everything else). 

Does this seem reasonable? cc @bamos @vshobha @mhmukadam

**Comment by vshobha** [comment]
Good catch @luisenp, I didn't see that the `aux_vars` get passed in as part of the `optimizer_kwargs` dictionary in the `TheseusLayer.forward` function. 

I actually like the current design where the user doesn't have to think about what variables are `optim_vars` vs `aux_vars` in the `TheseusLayer`. My suggestion would be to check `optimizer_kwargs` for `aux_vars` (and other similar kwargs might be confusing for the user) and throw an error if it is present there. 

We should probably also see if we can find other places in the API where such errors may happen.

**Comment by mhmukadam** [comment]
I don't think `aux_vars` weren't meant to be passed separately into `optimizer_kwargs` but instead be only included in `input_data`. The `optimizer_kwargs` go all the way down till [`compute_delta`](https://github.com/facebookresearch/theseus/blob/main/theseus/optimizer/nonlinear/levenberg_marquardt.py#L49) of a leaf class in the optimizer class hierarchy and is meant for other params.

I agree having a single input dict to `TheseusLayer.forward` would be cleaner. For simplicity, we can recommend `input_data = {optim_vars, aux_vars}` but this would be up to how the user sets things up. If we all agree here, then we should make this clear in the documentation what the contract is and take a pass over all tutorial/example/unit-test to make things consistent. This should resolve the current issue.

Also the `aux_vars` going into the `input_data` would be a union of all the individual `aux_vars` going into all the `CostFunction`s. I am not sure if any change is needed for this.

**Comment by vshobha** [comment]
> I don't think `aux_vars` weren't meant to be passed separately into `optimizer_kwargs` but instead be only included in `input_data`. 

Can you clarify this? Do you want to allow or disallow `aux_vars` in `optimizer_kwargs`? My previous comment was suggesting disallowing `aux_vars` explicitly, to ensure users easily avoid the kind of bug/incorrect API usage Brandon found. 

> I agree having a single input dict to `TheseusLayer.forward` would be cleaner. For simplicity, we can recommend `input_data = {optim_vars, aux_vars}` but this would be up to how the user sets things up. If we all agree here, then we should make this clear in the documentation what the contract is and take a pass over all tutorial/example/unit-test to make things consistent. This should resolve the current issue.

> Also the `aux_vars` going into the `input_data` would be a union of all the individual `aux_vars` going into all the `CostFunction`s. I am not sure if any change is needed for this.

In current API, the user does not need to specify which variables are `aux_vars` and which are `optim_vars`. I'd suggest keeping that design if possible, because it reduces effort for the user.

**Comment by mhmukadam** [comment]
> Can you clarify this? Do you want to allow or disallow aux_vars in optimizer_kwargs? My previous comment was suggesting disallowing aux_vars explicitly, to ensure users easily avoid the kind of bug/incorrect API usage Brandon found.
Yes, I meant we should not pass aux_vars to optimizer_kwargs. I like the idea of explicitly disallowing this.

> In current API, the user does not need to specify which variables are aux_vars and which are optim_vars. I'd suggest keeping that design if possible, because it reduces effort for the user.
Agreed, that makes sense.
