### ISSUE TITLE
The efficiency of objective.add(CostFunction)

### ISSUE THREAD

**Issue by Christopher6488** [facebookresearch/theseus#301]
## ❓ Questions and Help
I want to construct 20000+ optimization problem and call objective.add(CostFunction) for each problem in a for loop. I found that the loop velocity is slower and slower, and objective.add(CostFunction) functions are increasingly time-consuming. The total time is about 200+ seconds. How can I fix this problem?

**Comment by Christopher6488** [comment]
I have found the reason and fixed it. I will launch a PR.

**Comment by mhmukadam** [comment]
@Christopher6488 thanks for raising this. Yes the PR would be great to understand the details and also great that you found a fix too!

**Comment by Christopher6488** [comment]
> 

Thanks for replying! I have two questions:I have run `python -m pytest theseus -m "not cudaext"` to conduct unit test after fixing the issue. However, the terminal logs `theseus/tests/test_theseus_layer.py:366: AssertionError`.  This error seems to have nothing to do with my changes(even if I don't make any changes, the error still exists). Thus, how will I fill out the Checklist in PULL_REQUEST_TEMPLATE.MD? The changes in Objective.add(CostFunction) are only to improve the execution speed and  does not bring about functional changes. Do

**Comment by Christopher6488** [comment]
Thanks for replying! I have two questions:
1. I have run python -m pytest theseus -m "not cudaext" to conduct unit test after fixing the issue. However, the terminal logs theseus/tests/test_theseus_layer.py:366: AssertionError. This error seems to have nothing to do with my changes(even if I don't make any changes, the error still exists). Thus, how will I fill out the Checklist in PULL_REQUEST_TEMPLATE.MD?

2. The changes in Objective.add(CostFunction) are only to improve the execution speed and does not bring about functional changes. Do I need to add test? The test in test_objective.py has tested the safety of Objective.add(CostFunction).

**Comment by luisenp** [comment]
Hi @Christopher6488, thanks for the contribution! If you open a PR with your current version I'm happy to take a look at give some feedback. It'd be easier to answer your questions if I can look at the code.
