### ISSUE TITLE
Automated check for Cost's jacobian method

### ISSUE THREAD

**Issue by maurimo** [facebookresearch/theseus#321]
## 🚀 Feature
Automated check for Cost's jacobian method

## Motivation
Hand-writing jacobians is complex an error prone. We might still do it because it's faster than using numeric_jacobian or automated differentiation. But it should be easy to check that our implementation is correct.

## Pitch
We can add a `verify_jacobians` method in the optimizer, which will evaluate 100 costs per type, computing both the numeric_jacobian and the hand-written jacobian method, and verify if they are correct. It might be silent if they match very well eg < 1e-6, and compute and print maximum error otherwise (the user might decide to ignore the problem as the numeric jacobian might occasionally be unstable).

## Alternatives
None I'm aware of.

## Additional context
We should not have to compute manually derivatives anymore. If we do, it should be easy to check they are correct ;)

**Comment by mhmukadam** [comment]
Good idea! Can we instead set this up a unit test utility for cost functions instead so that the optimizer and other internals don't slow down during actual learning/inference?
