### ISSUE TITLE
Error with torch.autograd.set_detect_anomaly(True)

### ISSUE THREAD

**Issue by JayYe99** [facebookresearch/theseus#331]
## 🐛 Bug

I noticed that when set the torch.autograd.set_detect_anomaly flag, here comes an error regarding vmap. I'm wondering if this error will influence the backward process.

> RuntimeError: vmap: It looks like you're calling .item() on a Tensor. We don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. If error is occurring somewhere inside PyTorch internals, please file a bug report.

## Steps to Reproduce

You can reproduce this error simply with the homography_estimation example provided in this repo.
1. Add the line `torch.autograd.set_detect_anomaly(True)` in homography_estimation.py
2. Run homography_estimation.py

## Expected behavior
The error goes as follows:
![image](https://user-images.githubusercontent.com/52844723/196616222-40907f94-e78a-4555-922a-8bda05b577a6.png)

## System Info

- OS (e.g., Linux): Linux
- Python version: 3.8.3
- GPU models and configuration:
- CUDA version: 11.6
- pip/conda dependencies packages versions: 
- Any other relevant information:

**Comment by luisenp** [comment]
Hi @JayYe99, thanks for the report. This looks in fact like a bug in functorch when using anomaly detection. See this [issue](https://github.com/pytorch/functorch/issues/1049). I'll close this issue, as it doesn't seem to be on our side.
