### ISSUE TITLE
Ellipsoidal damping for SparseSolver

### ISSUE THREAD

**Issue by mhmukadam** [facebookresearch/theseus#35]
`A' = A + damping * diag(A + eps)`

**Comment by maurimo** [comment]
Very hard to fix using Cholmod on CPU! The reason is that we only give A to Cholmod, and it will compute At*A internally, plus possibly spherical damping. The new CUDA LU-based solver will support ellipsoidal damping from the beginning.

**Comment by luisenp** [comment]
Do we have an error in place for this? For consistency, we should probably allow the user to pass this parameter when using Cholmod and either throw an error/warning somewhere.

**Comment by mhmukadam** [comment]
Agreed, we should raise an error here. There are other possible places where we need such errors to account for incompatible combinations of solvers/supported settings. Maybe flag a separate issue to do a sweep for these.

**Comment by luisenp** [comment]
@maurimo I forgot what the status of this. Can you remind me which of our sparse solvers (if any) currently support this?

**Comment by maurimo** [comment]
Can work on Cuda-LU, will work with BaSpaCho (as Jt x J is/will be computed externally), no chance with Cholmod as it's computing Jt x J internally (adding only possibly one constant to the diagonal). To make it work with Cholmod need to implement externally the operation Jt x J (but I think BaSpaCho will prove to superseed Cholmod also as CPU-only solver).
