### ISSUE TITLE
Unknown Variable Shape Print Out

### ISSUE THREAD

**Issue by xphsean12** [facebookresearch/theseus#375]
## 🚀 Feature
Is it possible to shut down the tensor shape auto printout?

![image](https://user-images.githubusercontent.com/52436595/203741852-e1d4a2c0-4b9a-4e75-bc06-b95aee6bdbd1.png)

## Motivation

When I train the model with large number of variable, there are many tensor shape prints out. And it takes a long time for me to find the information I printed. I have checked the source code but can not find where to turn it off.

## Pitch
A simple keyword like "verbose" to determine whether to keep printing the tensor shape.

**Comment by luisenp** [comment]
Hi. Thanks for reporting, this is not intentional! Which version of the library are you using?

**Comment by luisenp** [comment]
Does this happen only under some conditions? Do you have some code that can reproduce this error? I just checked out tag 0.1.3 and ran several of our examples and didn't notice any such print statements.

**Comment by xphsean12** [comment]
> Does this happen only under some conditions? Do you have some code that can reproduce this error? I just checked out tag 0.1.3 and ran several of our examples and didn't notice any such print statements.

Thanks! After examination, I found that it is my own mistake. I mistakenly print out the shape of the output error. Thanks for replying again. Could you please help to close this issue?
