### ISSUE TITLE
module 'torch.utils.cpp_extension' has no attribute 'CUDA_GCC_VERSIONS'

### ISSUE THREAD

**Issue by EcustBoy** [facebookresearch/theseus#376]
## ❓ Questions and Help
Hi author~ I follow your installation step :
1. I create conda env with python3.8 + torch1.9 + cu111 (because the original cuda installed in my machine is 11.1 by running **nvcc -V**)
2. Then I choose to build from source ：
![image](https://user-images.githubusercontent.com/32817744/203906066-817b5b2e-9d80-448c-96ff-66906ac8d1c8.png)
but the following error occurs:
![image](https://user-images.githubusercontent.com/32817744/203906114-b827fd6b-8718-4c4c-bed3-35dc1a40afa3.png)

it seems like pytorch version is not right? So I upgrade to **torch 1.11 + cu113**，but the same error is still reported.

I would like to ask what the possible reason is and can you give some advice？ I'll thanks for your reply~

**Comment by luisenp** [comment]
Hi @EcustBoy. Sorry for the delay, I lost track of this issue. Looks like `CUDA_GCC_VERSIONS` was only added after torch 1.12. Are you hard constrained to use torch <1.12?

**Comment by luisenp** [comment]
Hi @EcustBoy. Were you able to check if the proposed fix works for you?
