### ISSUE TITLE
Allow constant inputs to cost functions to be passed as floats

### ISSUE THREAD

**Issue by mhmukadam** [facebookresearch/theseus#38]
...and converted to `Variable` objects internally. 

This includes things like `dt` in GP cost function, and `cost_eps` or `cell_size` in `Collision2D`.

**Comment by jeffin07** [comment]
@luisenp @mhmukadam I woukd like to work on this can you please guide me ?

**Comment by luisenp** [comment]
Some of our cost functions receive `Variable` objects to represent quantities that are typically floats scalar. It would be more user friendly to change these functions to accept float as input, and wrap the value into a `Variable` internally. 

For example, the `dt` argument in [this](https://github.com/facebookresearch/theseus/blob/main/theseus/embodied/motionmodel/double_integrator.py#L21) function. For an example of how we handle this in other places, you can take a look at the code for [ScaleCostWeight](https://github.com/facebookresearch/theseus/blob/main/theseus/core/cost_weight.py#L61).

**Comment by mhmukadam** [comment]
One minor clarification: accept either float or Variable as an input via `Union[float, Variable]`. Do we also want to include `torch.Tensor` here @luisenp?

**Comment by luisenp** [comment]
@mhmukadam Oh yes, thanks for clarifying, we want keep support for `Variable` input as well! 

Including `torch.Tensor` would be good also.
