### ISSUE TITLE
Gradient scaling bug in implicit/truncated backward mode

### ISSUE THREAD

**Issue by mhmukadam** [facebookresearch/theseus#39]
[See comment in original feature PR](https://github.com/facebookresearch/theseus/pull/29#issue-1077713367).

**Comment by bamos** [comment]
Resolved in the attached commit! :-)

@luisenp and I found that it was related to not using a step size of 1 in the second loop that the truncated/implicit modes backprop through

```python
theseus(diff*)$ ./examples/backward_modes.py
--- backward_mode=FULL                                     
[ 0.09670612 -0.7900081   0.08778726  0.13497931  0.21781093 -0.20041543
  0.11018689 -1.5431342   0.13462512 -0.23546126]

--- backward_mode=IMPLICIT
[ 0.09670904 -0.7900324   0.08778992  0.1349834   0.21781752 -0.20042153
  0.11019021 -1.5431813   0.1346292  -0.23546849]

--- backward_mode=TRUNCATED, backward_num_iterations=5
[ 0.09670907 -0.7900323   0.08778992  0.13498342  0.21781753 -0.20042154
  0.11019026 -1.5431811   0.13462925 -0.23546834]

--- Numeric derivative
[ 0.09670693 -0.7900125   0.08778608  0.13497717  0.21781142 -0.20041636
  0.11019139 -1.54313637  0.13462317 -0.2354647 ]

=== Runtimes
Forward: 1.95e-02 s +/- 1.31e-03 s
Backward (FULL): 5.42e-03 s +/- 3.42e-04 s
Backward (IMPLICIT) 6.90e-04 s +/- 7.95e-05 s
Backward (TRUNCATED, 5 steps) 1.22e-03 s +/- 1.04e-04 s
```

**Comment by mhmukadam** [comment]
>  not using a step size of 1 in the second loop that the truncated/implicit modes backprop through

Awesome find! We should keep this in mind when we use LM as well.

**Comment by luisenp** [comment]
If I understand the latest changes correctly, the code now works with any step size value. The caveat is that implicit/truncated overrides the step size to 1.0 for the last "grad_enabled" optimizer iterations. I think this is a reasonable workaround, since in the typical case the gradient magnitude should be small at that point. @bamos, can you confirm?

**Comment by bamos** [comment]
Yes that's right
