### ISSUE TITLE
error and errorSquaredNorm can optionally take in variable data 

### ISSUE THREAD

**Issue by luisenp** [facebookresearch/theseus#4]
## 🚀 Feature

**API improvement in `Objective`:** `error` and `errorSquaredNorm` can optionally take in `var_data` which if passed would call `update` internally. Document the behavior that if `var_data` is passed this will `update` the objective.

## Motivation

Facilitates usage for cases where only error needs to be queried (w/o running optimization or even updating the variables).

## Pitch

Following ways to use this api after:
1. Get `error` on current internal values: call `error ` without passing any `var_data`
2. Get `error` on new values w\ update to objective: call `error` and pass `var_data`
3. Get `error` on new values w\o update to objective: call `error`, pass `var_data` and `True` optional flag to not update objective

**Comment by jeffin07** [comment]
@luisenp I am intrested in this issue.Can you please guide me to fix this ?

**Comment by luisenp** [comment]
As a first step, if you haven't already, I suggest to take a look at the 3 first tutorials to get a sense of how Theseus API works.

In regards to this issue, the goal is to modify [this](https://github.com/facebookresearch/theseus/blob/main/theseus/core/objective.py#L340) method so that it includes two new kwargs:

* `input_data: Optional[Dict[str, torch.Tensor]]=None`.
* `also_update: bool=False`
 
If `input_data` dictionary is given, then, before doing anything else in this method, you need to call `objective.update(input_data=input_data)` so that variables are updated with the given dictionary. However, if `also_update=False`, you'll also need to store the old variable values being overridden, so that after computing the error, the method can set the variables to their previous values. It'll be useful to also look at the code in `objective.update()`.

A similar procedure can be used for `errorSquaredNorm()`.

Let me know if you have any questions.

**Comment by jeffin07** [comment]
@luisenp  we need to check for `also_update` if `input_data` is present right? Also how to store the old varibles? is a `self.old_varibales = self._all_variables` is enough before calling `self.update()`

**Comment by luisenp** [comment]
Hi @jeffin07. In the case that `input_data` is not present, we can just ignore `also_update` and proceed with the current behavior. 

To store the old variables we don't need to create a new member variable, it can be scoped just to the error function. Also, I think a simple assignment would fail, since it will just create a pointer to the old dictionary which points to the variable objects being updated. What we have to do is create a new dictionary that has the same keys (variable names), and each key is mapped to the current data tensor of the corresponding variable (e.g., `old_data["var_1"] = self.optim_vars["var_1"].data`).

After the error function is computed you can then update all variables with the tensor that was stored. Something like `self.update(old_data)` should be enough to do this.

**Comment by jeffin07** [comment]
@luisenp  is this okay ?
```
    def error(self, input_data: Optional[Dict[str, torch.Tensor]]=None, also_update: bool=False) -> torch.Tensor:
        old_data = {}
        if input_data is not None:
            self.update(input_data=input_data)
            if !also_update:
            for var in self._all_variables:
                old_data[var] = self.optim_vars[var].data
            self.update(old_data)
        error_vector = torch.zeros(self.batch_size, self.dim()).to(
            device=self.device, dtype=self.dtype
        )
        pos = 0
        for cost_function in self.cost_functions.values():
            error_vector[
                :, pos : pos + cost_function.dim()
            ] = cost_function.weighted_error()
            pos += cost_function.dim()
        self.update(old_data)
        return error_vector
```

**Comment by luisenp** [comment]
Hi @jeffin07, it's one the right track. However, we need to save tensors to `old_data` before calling `self.update` because doing so will overwrite the content of all `var.data` so we will lose the old values. And we only need to call `self.update(old_data)` once at the end of the method, and only if `input_data` is not `None` and `not also_update`.  

Once this is implemented, we should also add unit tests [here](https://github.com/facebookresearch/theseus/blob/main/theseus/core/tests/test_objective.py) checking that this method is behaving as intended. 

Thanks!

**Comment by jeffin07** [comment]
@luisenp Thank you for the explanation. About the multiple `self.update(old_data)` that was a mistake from my side i forgot to remove that.But I have one doubt as you said in earlier comment we need to call update before doing anaything if input_data is present right?.so that call will overwrite the data right ? 


> If `input_data` dictionary is given, then, before doing anything else in this method, you need to call `objective.update(input_data=input_data)` so that variables are updated with the given dictionary. However, if `also_update=False`, you'll also need to store the old variable values being overridden, so that after computing the error, the method can set the variables to their previous values. It'll be useful to also look at the code in `objective.update()` to get a sense of how to manipulate the variable values stored internally.
> 

Sorry for asking multiple times about the same, Is this changes looks good ?.Because before moving to tests i want to make sure the function works perfectly as you intented


```
    def error(self, input_data: Optional[Dict[str, torch.Tensor]]=None, also_update: bool=False) -> torch.Tensor:
        old_data = {}
        if input_data is not None:
            self.update(input_data=input_data)
            if !also_update:
            for var in self._all_variables:
                old_data[var] = self.optim_vars[var].data
        error_vector = torch.zeros(self.batch_size, self.dim()).to(
            device=self.device, dtype=self.dtype
        )
        pos = 0
        for cost_function in self.cost_functions.values():
            error_vector[
                :, pos : pos + cost_function.dim()
            ] = cost_function.weighted_error()
            pos += cost_function.dim()
        if input_data is not None and !also_update:
            self.update(old_data)
        return error_vector


```

**Comment by jeffin07** [comment]
Hi @luisenp I have some doubts regarding writing test for objective error. The new conditions for objective error has to in `test_objective_error` function right ?Also it would be helpful if you can tell me your thoughts for the test function.

**Comment by luisenp** [comment]
Hi @jeffin07. That's the correct test, yes. I noticed that the code for that test was really old, and it could be made simpler with some of the standard variables and cost function that we have now. I made a new [version](https://github.com/facebookresearch/theseus/blob/main/theseus/core/tests/test_objective.py#L250), which is hopefully easier to follow. 

You can just add some additional code after line 281 that will tests that the functions follow the behavior we discussed above when passing other tensor values for `v1_data` and `v2_data` (and using `_check_error_for_data`).

**Comment by jeffin07** [comment]
@luisenp I have added test and checked, it passed all except `theseus/tests/test_theseus_layer.py::test_backward_levenberg_marquardt_leo`
Is this because of my edit in `core/objective.py` or something else in previous commits ?. Because i only edited `core/objective.py`. Sorry if i  miss something

**Comment by luisenp** [comment]
Hi @jeffin07. Can you post a screenshot of the error. Also, if you make a pull request from your fork to our `main` branch, I can turn on CI tests and see your code and test results as well.

**Comment by jeffin07** [comment]
@luisenp  I have made a PR #105. Please review
