### ISSUE TITLE
Compute Jacobians Error

### ISSUE THREAD

**Issue by Jeff09** [facebookresearch/theseus#444]
## 🐛 Bug

Hi, I have used Theseus in some of trajectory planning code. My use case is to use Theseus to optimize the trajectory outputted from some neural networks according to other constraints, like free-collision, and following the lane center. However, some errors appears when computing the jacobians. 
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/13411170/213791986-7e0206ed-ebd6-48ed-a900-c8de781836e0.png">

## System Info

- OS (e.g., Linux): Linux
- Python version: 3.9
- GPU models and configuration: Nvidia Tesla V100
- CUDA version: 11.1
- pip/conda dependencies packages versions: theseus 0.1.3
- Any other relevant information:

**Comment by luisenp** [comment]
Hi @Jeff09, have you tried setting `autograd_mode="dense"`, when you create the `AutoDiffCostFunction`, does that work? Also, have you checked that your error function code is compatible with `functorch`'s `vmap`?

**Comment by Jeff09** [comment]
Thanks @luisenp. I have tried `autograd_mode="dense"` when using `AutoDiffCostFunction`, it works.
