### ISSUE TITLE
Revisit Lie group consistency checks

### ISSUE THREAD

**Issue by luisenp** [facebookresearch/theseus#521]
We have observed some 64-bit SE2 tensors with cosines slightly larger than ones sneaking through after application of retraction maps. We should consider making the Lie group checks stronger to prevent issues like this. Another option would be to normalize all `exp_map` outputs (e.g., [here](https://github.com/facebookresearch/theseus/blob/main/theseus/geometry/se2.py#L259)).

**Comment by mhmukadam** [comment]
Is this happening in the new Lie groups too?

**Comment by mhmukadam** [comment]
Flagging unresolved comments from #528 that need to be resolved with this issue.
- need greater eps for the log and exp derivative computation
- We might need to add `so3_derivative_near_zero_eps_floatxx`

**Comment by luisenp** [comment]
Closed by #544
