### ISSUE TITLE
Range Measurement

### ISSUE THREAD

**Issue by codeaddict00** [facebookresearch/theseus#592]
## 🚀 Feature
A range measurement model between a Pose and a Point.
Similar to what exists in GTSAM: https://github.com/borglab/gtsam/blob/develop/gtsam/sam/RangeFactor.h
It would be good to have this along with the [between factor](https://github.com/facebookresearch/theseus/tree/240e1206329d42fedd40399684d6e17e455c6645/theseus/embodied/measurements). 

## Motivation

Makes Range-based SLAM and Proximity-based loop closing possible, and many more applications.

## Alternatives

If you can't implement it. Could you give as much context and pointers as possible to help with the developpement of a Range factor in Theseus. 
- What functions already built-in could be leveraged?
- How to compute the Jacobians, and how to test if their implementation is correct?

Thanks in advance for your time!

**Comment by luisenp** [comment]
Hi @codeaddict00. Sorry for the delay in getting back to you.

This should be relatively easy to implement in 2D. The following functions should be useful:

* Need to write a wrapper in your cost function for converting either [Point2](https://github.com/facebookresearch/theseus/blob/main/theseus/geometry/point_types.py#L31) or [SE2](https://github.com/facebookresearch/theseus/blob/main/theseus/geometry/se2.py) into an xy-vector, and return its jacobian. For Point2 this is trivial, and for SE2 you can use [xy](https://github.com/facebookresearch/theseus/blob/main/theseus/geometry/se2.py#L143).
* Create the error [implementation](https://github.com/facebookresearch/theseus/blob/240e1206329d42fedd40399684d6e17e455c6645/theseus/embodied/measurements/between.py#L34) that returns e = p1_xy - p2_xy (the error is weighted and squared automatically by theseus elsewhere).
* Create the [jacobian](https://github.com/facebookresearch/theseus/blob/240e1206329d42fedd40399684d6e17e455c6645/theseus/embodied/measurements/between.py#L38) implementation. For this case, the jacobian is just the jacobian of `xy()` operation wrapper, multiplied by the correct sign for each variable.
* Make sure you register the variables as shown [here](https://github.com/facebookresearch/theseus/blob/240e1206329d42fedd40399684d6e17e455c6645/theseus/embodied/measurements/between.py#L26).
* You can test your jacobians with [this](https://github.com/facebookresearch/theseus/blob/240e1206329d42fedd40399684d6e17e455c6645/theseus/utils/utils.py#L155) function.

For 3D the process is similar, but we don't have an implementation for `SE3.xyz()`, so we would need to add that first.

**Comment by codeaddict00** [comment]
Awesome thanks for your support and pointers! I will try this soon!
