### ISSUE TITLE
Not having an accurate result / error not match the cost

### ISSUE THREAD

**Issue by alwaysbyx** [facebookresearch/theseus#615]
## ❓ Questions and Help

I am following the simple example to solve a simple Model predictive control (1dimension) problem:
but got the incorrect result. 

Using LQR controller law u[0] should around -23, and the solver gives -11.4.

And also I was wondering why the error output is not the same as the cost I defined. Thanks! 
```

        A = th.Variable(torch.ones(1,1), name='A')
        B = th.Variable(torch.ones(1,1), name='B')
        Q = th.Variable(torch.ones(1,1), name='Q')
        R = th.Variable(torch.ones(1,1), name='R')
        x_init = th.Variable(torch.ones(1,1),name='x0')
        us = [th.Vector(1, name=f'action{t}') for t in range(self.T)]
        def cost_fn(optim_vars, aux_vars):
            us_ = optim_vars
            A_, B_, Q_, R_, x_init_ = aux_vars
            x_lists_ = [x_init_]
            cost = []
            for t in range(self.T):
                if t == 0: 
                    x_lists_.append(x_lists_[-1].tensor @ A_.tensor +  us_[t].tensor @ B_.tensor)
                    cost.append(Q_.tensor * x_lists_[0].tensor.square()) + R_.tensor * us_[t].tensor.square())
                else: 
                    x_lists_.append(x_lists_[-1] * A_.tensor + us_[t].tensor * B_.tensor)
                    cost.append(Q_.tensor * x_lists_[t].square()  + R_.tensor * us_[t].tensor.square())
            return torch.cat(cost_list, axis=-1)
        optim_vars = us
        aux_vars = [A, B, Q, R, x_init]
        cost_function = th.AutoDiffCostFunction(
            optim_vars, cost_fn, self.T, aux_vars=aux_vars, name="cost_fn"
        )
        objective = th.Objective()
        objective.add(cost_function)
        optimizer = th.LevenbergMarquardt(
            objective,
            max_iterations=10,
            step_size=1.0,
        )
        layer = th.TheseusLayer(optimizer, vectorize=False)

        theseus_inputs = {
                    "A": 0.5 * torch.ones(1,1), 
                    "B": 1.0 * torch.ones(1,1),
                    "Q": 10.0 * torch.ones(1,1),
                    "R": 1.0 * torch.ones(1,1),
                    "x0": 50.0 * torch.ones(1,1),
                    "action": torch.ones(1,self.T),
                }
          with torch.no_grad():
              updated_inputs, info = layer.forward(
                  theseus_inputs, optimizer_kwargs={"track_best_solution": True, "verbose":True})

```

**Comment by luisenp** [comment]
Hi @alwaysbyx, sorry for the long delay, I've been incredibly busy. The code you shared above doesn't run, I had to make some modifications: set `self.T` to some value (I used 10), and replace `torch.cat(cost_list)` with `torch.cat(cost)`, and also fix some parenthesis issues. As such, I cannot reproduce the numbers you are reporting.

**Comment by luisenp** [comment]
Regarding the error output, I'm assuming you are referring to the optimizer logs. If so, this corresponds to the sum of weighted **squared** costs, divided by two; [here is the code](https://github.com/facebookresearch/theseus/blob/main/theseus/core/objective.py#L37).

**Comment by alwaysbyx** [comment]
Hi, I am sending the code file link to your email and compare a simple problem (MPC with disturbance) of theseus and gurobi solver. Do you receive that email? I believe you can directly run that file and compare the performance.

**Comment by alwaysbyx** [comment]
Hi Thank you for your comments. I do not implement xu[t] == x[t] * u[t] in Theseus but this holds when evaluating the dynamics in Theseus (B_.tensor * us_[t].tensor * xs_true[-1]).
