### ISSUE TITLE
question about 'Objective.error_squared_norm()'

### ISSUE THREAD

**Issue by WeiXiCZ** [facebookresearch/theseus#620]
## ❓ Questions and Help
Hello, when I run the following code, it comes to the error:
![image](https://github.com/facebookresearch/theseus/assets/86120782/797621f8-9d46-4e69-91d8-1a6b49a18ab6)
What's wrong with this🥺

**Comment by luisenp** [comment]
Hello, this method was deprecated a few versions ago, and it's now replaced by `objective.error_metric()`, which by default returns the squared error norm. 

Did you find this usage in one of our examples?

**Comment by rutabaga110** [comment]
oh I found it in examples! thanks a lot!
your work is so wonderful, I'll study it carefully.

**Comment by luisenp** [comment]
Thanks for your kind words! 

Could you send me a link to the example where you found this usage? It shouldn't be there, as this function doesn't exist anymore. Thanks!
