### ISSUE TITLE
undefined symbol: dsyrk_

### ISSUE THREAD

**Issue by shengtsui** [facebookresearch/theseus#630]
## ❓ Questions and Help
I've successfully installed `baspacho`. However, I got the following error when I try `import theseus.extlib.baspacho_solver`. Do you know how to solve this issue?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/stsui/theseus/theseus/extlib/baspacho_solver.cpython-310-x86_64-linux-gnu.so: undefined symbol: dsyrk_
```

**Comment by luisenp** [comment]
Hi @shengtsui. I'm not familiar with this error. Are you able to use our Baspacho solver if you install with `pip install theseus-ai`?

**Comment by shengtsui** [comment]
I found out a solution by preloading MKL package.
`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libmkl_def.so:/usr/lib/x86_64-linux-gnu/libmkl_avx2.so:/usr/lib/x86_64-linux-gnu/libmkl_core.so:/usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so:/usr/lib/x86_64-linux-gnu/libmkl_intel_thread.so:/usr/lib/x86_64-linux-gnu/libiomp5.so`

**Comment by luisenp** [comment]
Thanks for sharing the solution!
