### ISSUE TITLE
how to deploy a theseus trained model to device? 

### ISSUE THREAD

**Issue by baodingge** [facebookresearch/theseus#643]
## ❓ Questions and Help

I trained a model using the Theseus library, but i have no idea about how to deploy it on hardware. Theseus uses automatic differentiation and iterative solving, making it impossible to directly export the ONNX model like the Torch model and further run on specified hardware. If ceres is used instead of theseus during deployment, how can we ensure the accuracy of both? Are there any suggestions?
thanks very much.
best

**Comment by luisenp** [comment]
Hi @baodingge. Unfortunately we haven't worked on this use case so far and not planning to add support for this in the near future.
