### ISSUE TITLE
Fail to install on Windows

### ISSUE THREAD

**Issue by BigPotato-H** [facebookresearch/theseus#649]
## ❓ Questions and Help
i was installing from source using: >pip install -e .
ERROR: Could not build wheels for scikit-sparse, which is required to install pyproject.toml-based projects

then i went to suitesparse: https://github.com/jlblancoc/suitesparse-metis-for-windows
 and installed it with cmake from source.

here i dont know how to continue installing Theseus. because [pip install -e .] still doesn't work.

can anyone give some help?

best wishes!
![捕获](https://github.com/facebookresearch/theseus/assets/81399373/3e28c585-6d31-4d4e-90c2-15bd0735a585)

**Comment by BigPotato-H** [comment]
i m still trying to install scikit-sparse on windows.
install c++ suitesparse using cmake, referring to 
https://github.com/xmlyqing00/Cholmod-Scikit-Sparse-Windows
i used the latest version of scikit-sparse, here :
https://github.com/scikit-sparse/scikit-sparse
modify the setup.py, specially the include dir and lib dir. 
ensure the c++ suitesparse include and complied lib dir are correctly modified.
if u come across some problems like:
 '*.h' file can't be found, or '*.lib' file can't be linked
try to include the special directory of the '*.h' or the '*.lib'

now scikit-sparse is successfully installed in the conda environment on windows. 
i m trying to reinstall Theseus. new error comes, so sad.
![Uploading 捕获3.PNG…]()

**Comment by luisenp** [comment]
Hi @BigPotato-H. I don't have a lot of experience using Theseus of Windows, but what I recall is that you could install suitesparse from conda instead of pip, without having to compile from source. Did you try this?

**Comment by BigPotato-H** [comment]
> Hi @BigPotato-H. I don't have a lot of experience using Theseus of Windows, but what I recall is that you could install suitesparse from conda instead of pip, without having to compile from source. Did you try this?

Thanks for this important suggestion "install suitesparse from conda instead of pip", i didn't try this solution yet. Because i finally succeeded using Theseus on Windows WSL after two weeks' struggle on environment deployment on Windows. But next time when i have more free time, i will try it out.  Thank you for your time and effort again.
