### ISSUE TITLE
Batched optimization

### ISSUE THREAD

**Issue by praveenVnktsh** [facebookresearch/theseus#652]
Hi!

I am trying to optimize a pose through a network for alignment between multiple sensors.

My network can handle images of size BxCxHxW. I was a little confused as to how to perform batched optimizations through theseus (basically BxCxHxW -> Network -> BxCxhxw -> network -> Bx6x1 -> optimizer -> Bx6x1) 

Is a workflow like this possible without iterating through each of the samples in the batch? I did not entire.ly understand the workflow.

I saw this tutorial - https://github.com/facebookresearch/theseus/blob/main/tutorials/02_differentiating_theseus_layer.ipynb that seems to iterate through each of the samples. 

```
for epoch in range(num_epochs):
    epoch_loss = 0.
    epoch_b = []  # keep track of the current b values for each model in this epoch
    for i in range(num_batches):
        model_optimizer.zero_grad()
        data_x, data_y = data_batches[i]
        # Step 2.1: Create input dictionary for TheseusLayer, pass to forward function
        # The value for variable `a` is the updated `a_tensor` by Adam
        # Since we are always passing the same tensor, this update is technically redundant, 
        # we include it to explicitly illustrate where variable values come from.
        # An alternative way to do this (try it!)
        # would be to call `a.update(a_tensor)` before the learning loop starts
        # and just let Adam change its value under the hood (i.e., update only `x`, `y`, and `b`
        # inside the loop)
        theseus_inputs = {
            "a": a_tensor,
            "x": data_x,
            "y": data_y,
            "b": torch.ones((1, 1)),
        }
        updated_inputs, info = theseus_optim.forward(theseus_inputs)
        epoch_b.append(updated_inputs["b"].item())  # add the optimized "b" of the current batch to `epoch_b` list. 
                                                    # Note: here, we do not track the best solution, as we 
                                                    # backpropagate through the entire optimization sequence.
        # Step 2.2: Update objective function with updated inputs
        objective.update(updated_inputs)
        loss = cost_function.error().square().mean()
        # Step 2.3: PyTorch backpropagation
        loss.backward()
        model_optimizer.step()

        loss_value = loss.item()
        epoch_loss += loss_value
```

**Comment by luisenp** [comment]
Hi @praveenVnktsh. Yes, Theseus assumes that the first dimension of all variables is a batch dimension, where the batch is over optimization problems that are independent from each other. For example, you could have something like this:

* V1: vector with N degrees of freedom
* V2: vector with M degrees of freedom
* C(V1, V2): a cost function with an error dimension of P
* D(V1, V2): a cost function with an error dimension of Q

Then your input dict for the `TheseusLayer` can be of the form`{"V1": (B, N), "V2": (B, M)}`, where `B` is an arbitrary batch size. In this case:
* Evaluating C gives a tensor of shape (B, P)
* Evaluating D gives a tensor of shape (B, Q)
* Computing `layer.objective.error_metric()` will result in a tensor of shape `(B,)` with the squared error objective of ||C||^2 + ||D||^2 evaluated for each batch independently. 

Let me know if this explanation makes sense.

**Comment by praveenVnktsh** [comment]
That makes sense, thank you!
