### ISSUE TITLE
Bundle Adjustment example not using GPU?

### ISSUE THREAD

**Issue by vishnurohit87** [facebookresearch/theseus#653]
It seems like the bundle_adjustment.py is not using GPU while other examples such as homography_estimation.py do. Am I doing something incorrectly?

**Comment by luisenp** [comment]
Hi @vishnurohit87 this is correct, but you should be able to set the device to GPU with some small amount of work; you can use other examples as a guide. 

Sorry about this, I believe that back when we wrote this we hadn't still add vectorized cost function computation, so there was likely no advantage to using GPU. But this should no longer be the case now.
