### ISSUE TITLE
Once we converge on a solution we are satisfied with, we should test this with all of the first-order optimizers under `torch.optim`.

### ISSUE THREAD

**Issue by fantaosha** [facebookresearch/theseus#79]
Once we converge on a solution we are satisfied with, we should test this with all of the optimizer under `torch.optim`.

_Originally posted by @luisenp in https://github.com/facebookresearch/theseus/pull/75#discussion_r803153019_

**Comment by luisenp** [comment]
Closing this, since we'll want to do this before merging #75 anyway.

**Comment by fantaosha** [comment]
I reopen this issue since there is still some work to check after merging #75.

**Comment by fantaosha** [comment]
I close this after merging #74.
